'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Class Resource1
        
        Private Shared resourceMan As Global.System.Resources.ResourceManager
        
        Private Shared resourceCulture As Global.System.Globalization.CultureInfo
        
        <Global.System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")>  _
        Friend Sub New()
            MyBase.New
        End Sub
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("DroneSpace.Resource1", GetType(Resource1).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Shared Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property design5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("design5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dji_inspire_1_pro_black_edition_inc_lens__2__2313_p_2000x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dji_inspire_1_pro_black_edition_inc_lens__2__2313_p_2000x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dji_inspire_1_pro_landing() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dji_inspire_1_pro_landing", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_Inspire_1_Profront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_Inspire_1_Profront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dji_inspire_2_top() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dji_inspire_2_top", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property dji_mavic_air_arctic_white_drone_back() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dji_mavic_air_arctic_white_drone_back", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_MAVIC_AIR_WS_TOP() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_MAVIC_AIR_WS_TOP", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_SPARK_BL_01() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_SPARK_BL_01", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_SPARK_BL_02() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_SPARK_BL_02", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_SPARK_BL_03() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_SPARK_BL_03", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_SPARK_BL_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_SPARK_BL_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_SPARK_GN_04() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_SPARK_GN_04", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property DJI_SPARK_GN_side() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("DJI_SPARK_GN_side", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property djilogoblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("djilogoblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property djilogoblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("djilogoblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property djilogodarkblue() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("djilogodarkblue", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property djilogogrey() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("djilogogrey", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property djilogosilver() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("djilogosilver", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property djilogowhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("djilogowhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Inspire_1_Pro_Black_Edition__side_in_air_2__0_0() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inspire_1_Pro_Black_Edition__side_in_air_2__0_0", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Inspire_1_Pro_Black_Edition_front_on_ground_2048x() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inspire_1_Pro_Black_Edition_front_on_ground_2048x", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Inspire_1_Pro_Black_Edition_side_in_air_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inspire_1_Pro_Black_Edition_side_in_air_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Inspire_1_PRO_Black_Edition_sideground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Inspire_1_PRO_Black_Edition_sideground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property inspire1proBlack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspire1proBlack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property inspire2X_frontinair() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspire2X_frontinair", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property inspire2x4s() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspire2x4s", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property inspire2x5frontground() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspire2x5frontground", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property inspire2X7() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("inspire2X7", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Mavic_2_Pro_1() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mavic_2_Pro_1", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic_plat_folded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic_plat_folded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic_pro_folded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic_pro_folded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Mavic_Pro_Platinum_6_copy_e1504203431658() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mavic_Pro_Platinum_6_copy_e1504203431658", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Mavic2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mavic2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic2bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic2bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Mavic2front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Mavic2front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic2front2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic2front2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic2RC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic2RC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic2side() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic2side", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic2zoom_folded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic2zoom_folded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic2zoomfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic2zoomfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavic2zoomside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavic2zoomside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicAir_black_1200x1200() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicAir_black_1200x1200", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicairblack() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicairblack", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicairred() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicairred", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicairwhite() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicairwhite", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicairwhitefolded() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicairwhitefolded", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicpro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicpro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicproAW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicproAW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicprodown() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicprodown", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property mavicproinside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("mavicproinside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4pro() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4pro", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4profront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4profront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4proObsidian() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4proObsidian", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4proObsidian2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4proObsidian2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4proObsidianback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4proObsidianback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4proObsidianside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4proObsidianside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4proside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4proside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4prov2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4prov2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property p4prov2rc() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("p4prov2rc", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property pavicprofront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pavicprofront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property platinum_bottom() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("platinum_bottom", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property Remote_P4_Pro_Plus_Front() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Remote_P4_Pro_Plus_Front", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property s2_avatar_bad1e60756272c6527004db80ca75197() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("s2_avatar_bad1e60756272c6527004db80ca75197", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkallolors() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkallolors", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkback() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkback", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkfrontR() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkfrontR", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkline() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkline", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property SparkRC() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SparkRC", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkrc2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkrc2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkredfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkredfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkside() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkside", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparktopB() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparktopB", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property SparktopG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SparktopG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property SparktopW() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SparktopW", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkWfront() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkWfront", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property sparkWhand() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("sparkWhand", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend Shared ReadOnly Property SpsrksideY() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("SpsrksideY", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Class
End Namespace
